version: "3.8"

services:
    backend:
        build: .
        container_name: playacaribe-rental-car-backend
        restart: always
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - db
        volumes:
            - .:/var/www
        networks:
            - playacaribe-rental-car-network

    nginx:
        image: nginx:latest
        container_name: playacaribe-rental-car-server
        restart: always
        ports:
            - "8081:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
        networks:
            - playacaribe-rental-car-network

    db:
        image: mariadb
        container_name: mariadb
        restart: always
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./database/backups/playacaribe-rental-car-db.backup.sql:/docker-entrypoint-initdb.d/backup.sql
        networks:
            - playacaribe-rental-car-network

volumes:
    mariadb_data:

networks:
    playacaribe-rental-car-network:
        driver: bridge
